### Registro de usuario
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
  "fullName": "Julian",
  "email": "julian@gmail.com",
  "password": "paquita123"
}

###

### Inicio de sesión
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email": "julian@gmail.com",
  "password": "paquita123"
}

###

### obtener usuarios
GET  http://localhost:5000/api/users/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTFiMThmZjdjMjE4ZDkwYWRiNTE5YSIsImlhdCI6MTczODAxNjAwMiwiZXhwIjoxNzM4MDE5NjAyfQ.c9pzTNiTXgM31OhhU-rp4j7e2daHYGK7DaRkakoFxVE
###

### Crear un producto
POST http://localhost:5000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTFiMThmZjdjMjE4ZDkwYWRiNTE5YSIsImlhdCI6MTczODEyNTM1OCwiZXhwIjoxNzM4MTI4OTU4fQ.sl0R1JcNNjxq3Dg-_1UnmP6guK9jHCrje0mmngDxiR4

{
  "name": "Huebos",
  "description": "Leche deslactosada descremada",
  "price": 500,
  "category": "Cocina",
  "stock": 2
}

###

### Obtener productos (todos)
GET http://localhost:5000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTFiMThmZjdjMjE4ZDkwYWRiNTE5YSIsImlhdCI6MTczNzgxNDkxNSwiZXhwIjoxNzM3ODE4NTE1fQ.KIPaofEtiqPSRskePXTe1pqiE4-UJISKbPvlX0RmKYA

###

### Obtener productos por nombre
GET http://localhost:5000/api/products?name=ace
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTFiMThmZjdjMjE4ZDkwYWRiNTE5YSIsImlhdCI6MTczNzgxNDkxNSwiZXhwIjoxNzM3ODE4NTE1fQ.KIPaofEtiqPSRskePXTe1pqiE4-UJISKbPvlX0RmKYA

###

### Actualizar producto - buscar el id en la base de datos
PUT http://localhost:5000/api/products/6792cff9b184f39636800f26
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTFiMThmZjdjMjE4ZDkwYWRiNTE5YSIsImlhdCI6MTczNzgxNDkxNSwiZXhwIjoxNzM3ODE4NTE1fQ.KIPaofEtiqPSRskePXTe1pqiE4-UJISKbPvlX0RmKYA

{
  "name": "Jabón Líquido Antibacterial",
  "description": "Jabón líquido antibacteriano para manos",
  "price": 10000,
  "category": "Higiene",
  "stock": 120
}

###

### Eliminar producto - buscar el id en la base de datos
DELETE http://localhost:5000/api/products/6792cfb3b184f39636800f20
Content-Type: application/json

###